/*
 * arcane-route :: src/memory/MemoryManager.ts
 * Repository: owns ARCANE_MEMORY.md entirely
 * Uses Bun.write() for fast I/O
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ConfigManager } from '../core/ConfigManager.ts';
import { MemoryCorruptedError } from '../types/errors.ts';
import type { MemoryStatus } from '../types/index.ts';
import { MemoryEntry } from './MemoryEntry.ts';

const MEMORY_HEADER = `# ARCANE MEMORY
> Auto-generated by arcane-route. Source of truth for all AI file operations.
> Do NOT edit manually.

---

`;

const KEEP_RECENT_ON_COMPRESS = 20;

/**
 * Repository for ARCANE_MEMORY.md.
 * This class is the SOLE OWNER of the memory file.
 * All reads and writes go through this class.
 */
export class MemoryManager {
  private readonly filePath: string;
  private entries: MemoryEntry[] = [];
  private loaded = false;

  constructor(private readonly config: ConfigManager) {
    this.filePath = resolve(process.cwd(), config.getMemoryFilePath());
  }

  /**
   * Load (or initialize) ARCANE_MEMORY.md into memory.
   * If the file does not yet exist, it is created with the standard header.
   * Must be called before any read/write operation.
   */
  public async load(): Promise<void> {
    if (!existsSync(this.filePath)) {
      await this.writeRaw(MEMORY_HEADER);
      this.entries = [];
      this.loaded = true;
      return;
    }

    const raw = readFileSync(this.filePath, 'utf-8');
    this.entries = this.parse(raw);
    this.loaded = true;
  }

  /**
   * Lazily ensure the memory file is loaded before any operation.
   * Calls `load()` on first access if not yet loaded.
   */
  private async ensureLoaded(): Promise<void> {
    if (!this.loaded) await this.load();
  }

  /**
   * Append a new memory entry to ARCANE_MEMORY.md.
   * Uses Bun.write() for atomic write.
   */
  public async addEntry(entry: MemoryEntry): Promise<void> {
    await this.ensureLoaded();
    this.entries.push(entry);
    await this.persist();
  }

  /** Get all memory entries. */
  public async getEntries(): Promise<readonly MemoryEntry[]> {
    await this.ensureLoaded();
    return this.entries;
  }

  /** Get the N most recent entries. */
  public async getRecentEntries(count: number): Promise<readonly MemoryEntry[]> {
    await this.ensureLoaded();
    return this.entries.slice(-count);
  }

  /** Get total entry count. */
  public async countEntries(): Promise<number> {
    await this.ensureLoaded();
    return this.entries.length;
  }

  /**
   * Replace old entries with a compressed summary block, keeping only the
   * most recent `keepRecent` entries intact.
   * Used by DreamCommand after MemoryCompressor produces a summary.
   */
  public async replaceOldEntries(
    summary: string,
    keepRecent: number = KEEP_RECENT_ON_COMPRESS,
  ): Promise<void> {
    await this.ensureLoaded();
    const recent = this.entries.slice(-keepRecent);
    const compressedBlock = this.buildCompressedBlock(summary);
    this.entries = recent;
    await this.persistWithCompressed(compressedBlock);
  }

  /** Get memory file status. */
  public async getStatus(): Promise<MemoryStatus> {
    await this.ensureLoaded();
    const fileSizeBytes = existsSync(this.filePath) ? await Bun.file(this.filePath).size : 0;

    const raw = existsSync(this.filePath) ? readFileSync(this.filePath, 'utf-8') : '';

    return {
      entryCount: this.entries.length,
      fileSizeBytes,
      hasCompressedBlock: raw.includes('<!-- COMPRESSED BLOCK'),
      needsDream: this.entries.length >= this.config.getMemoryDreamThreshold(),
    };
  }

  /**
   * Return a formatted context string for injection into conversation history.
   * Truncates to `maxChars` (default 4 000) to stay within context window limits,
   * prepending an ellipsis indicator when the content is trimmed.
   */
  public async getMemoryContext(maxChars = 4_000): Promise<string> {
    await this.ensureLoaded();
    if (!existsSync(this.filePath)) return '';

    const raw = readFileSync(this.filePath, 'utf-8');
    if (raw.length <= maxChars) return raw;
    return `…[truncated]\n${raw.slice(-maxChars)}`;
  }

  // Serialization

  private serialize(entries: MemoryEntry[]): string {
    return MEMORY_HEADER + entries.map((e) => e.toMarkdown()).join('\n');
  }

  private parse(content: string): MemoryEntry[] {
    // Split on "## Session:" boundaries
    const blocks = content
      .split(/(?=^## Session:)/m)
      .filter((b) => b.trim().startsWith('## Session:'));

    const entries: MemoryEntry[] = [];
    for (const block of blocks) {
      const entry = MemoryEntry.fromMarkdown(block);
      if (entry) entries.push(entry);
    }
    return entries;
  }

  private buildCompressedBlock(summary: string): string {
    const ts = new Date().toISOString();
    return (
      `<!-- COMPRESSED BLOCK: entries compressed on ${ts} -->\n` +
      `> Prior sessions archived. Run \`arcane verify\` to check drift.\n` +
      `>\n` +
      `> **Summary:**\n` +
      summary
        .split('\n')
        .map((l) => `> ${l}`)
        .join('\n') +
      '\n' +
      `<!-- END COMPRESSED BLOCK -->\n\n`
    );
  }

  private async persist(): Promise<void> {
    const content = this.serialize(this.entries);
    await this.writeRaw(content);
  }

  private async persistWithCompressed(compressedBlock: string): Promise<void> {
    const recentContent = this.entries.map((e) => e.toMarkdown()).join('\n');
    const content = MEMORY_HEADER + compressedBlock + recentContent;
    await this.writeRaw(content);
  }

  /**
   * Write raw content to ARCANE_MEMORY.md using Bun.write().
   * @throws {MemoryCorruptedError} if the write fails.
   */
  private async writeRaw(content: string): Promise<void> {
    try {
      await Bun.write(this.filePath, content);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new MemoryCorruptedError(`Failed to write ARCANE_MEMORY.md: ${msg}`);
    }
  }
}
